// Copyright (c) 2025 CyberCortex Robotics SRL. All rights reserved
// Author: Sorin Mihai Grigorescu

// SLAM simulation:
//  - Set Camera interface to sim
//  - Set VisualSlam tracker to sim
//  - Set VehicleSimulator ReplayFromDB = false

Core:
{
    ID                  = 2
    BasePath            = ".."
    StartupFiltersView  = [200]
    Filters             = "bin/filters"
    LogFile             = "logs/robot_01.log"
    ReplayDB            = ""
}
Filters =
{
    DataChannel:
    {
        ID              = 1000
        Active          = True
        Type            = "CyC_COM_DATACHANNEL_FILTER_TYPE"
        InputSources    = (
                            {FilterID = 1, Description = "Lomacor Sever"}
                          )
        dt              = 0.1
        dt_Sequencing   = 0.1
        Parameters      = ({name="signaling_uri", value="wss://sig.cybercortex.ai:1920"})
    }
    LomacorSever:
    {
        ID              = 1
        Active          = True
        Type            = "CyC_LOMACOR_SERVER_FILTER_TYPE"
        IsNetworkFilter = True
        IsPublishable   = False
        ReplayFromDB    = False
        dt              = 0.5
        dt_Sequencing   = 0.5
        InputSources    = ({CoreID=1, FilterID=1, Description="Lomacor Server"})
        Parameters      = (
                            {name = "maps", value = "etc/maps/maps.csv"}
                          )
    }
    LomacorMaps:
    {
        ID              = 2
        Active          = True
        Type            = "CyC_LOMACOR_MAPS_FILTER_TYPE"
        IsPublishable   = True
        ReplayFromDB    = False
        dt              = 0.1
        dt_Sequencing   = 0.1
        InputSources    = ({FilterID = 1, Description = "Lomacor Sever"})
        Parameters      = ()
    }
    LomacorViz:
    {
        ID              = 200
        Active          = True
        Type            = "CyC_LOMACOR_VIZ_FILTER_TYPE"
        IsPublishable   = True
        ReplayFromDB    = False
        dt              = 0.1
        dt_Sequencing   = 0.1
        InputSources    = ({FilterID = 1, Description = "Lomacor Sever"})
        Parameters      = (
                            {name = "width", value = "300"},
                            {name = "height", value = "200"},
                          )
    }
}
