// Copyright (c) 2025 CyberCortex Robotics SRL. All rights reserved
// Author: Sorin Mihai Grigorescu

// SLAM simulation:
//  - Set Camera interface to sim
//  - Set VisualSlam tracker to sim
//  - Set VehicleSimulator ReplayFromDB = false

Core:
{
    ID                  = 1
    BasePath            = ".."
    StartupFiltersView  = []
    Filters             = "bin/filters"
    LogFile             = "logs/server.log"
    ReplayDB            = ""
}
Filters =
{
    DataChannel:
    {
        ID              = 1000
        Active          = True
        Type            = "CyC_COM_DATACHANNEL_FILTER_TYPE"
        InputSources    = (
                            {FilterID = 1, Description = "Lomacor Sever"}
                          )
        dt              = 0.1
        dt_Sequencing   = 0.5
        Parameters      = ({name="signaling_uri", value="wss://sig.cybercortex.ai:1920"})
    }
    LomacorSever:
    {
        ID              = 1
        Active          = True
        Type            = "CyC_LOMACOR_SERVER_FILTER_TYPE"
        IsPublishable   = True
        ReplayFromDB    = False
        dt              = 0.5
        dt_Sequencing   = 0.5
        InputSources    = ()
        Parameters      = (
                            {name = "maps", value = "etc/maps/maps.csv"}
                          )
    }
}
