// Copyright (c) 2025 CyberCortex Robotics SRL. All rights reserved
// Author: Sorin Mihai Grigorescu

FAMILY_NAME     = "Grigorescu"
GIVEN_NAME      = "Sorin"
AFFILIATION     = "CyberCortex Robotics"
ZENODO_URL      = "https://sandbox.zenodo.org"
ACCESS_TOKEN    = "LP7zVxmRWR4WTRVWNn8pMEnyBNxyTpAEui3E2pKPMZ00tpGdtzDrLZB2dgFN"    # sg@cybercortex.ai
#ACCESS_TOKEN        = "7B2u4nzmV3fgogOMirJF9SaHSllUucqBZoZQJnSG6BSh9NO6ODzKF6MgaTBZ" # s.grigorescu@unitbv.ro
