// Copyright (c) 2025 CyberCortex Robotics SRL. All rights reserved
// Author: Sorin Mihai Grigorescu

ZENODO_URL      = "https://sandbox.zenodo.org/api/deposit/depositions"
ACCESS_TOKEN    = "LP7zVxmRWR4WTRVWNn8pMEnyBNxyTpAEui3E2pKPMZ00tpGdtzDrLZB2dgFN"
