// Copyright (c) 2025 CyberCortex Robotics SRL. All rights reserved
// Author: Sorin Mihai Grigorescu

Core:
{
    ID                  = 1
    BasePath            = ".."
    StartupFiltersView  = []
    Filters             = "bin/filters"
    LogFile             = "logs/cyc.log"
    ReplayDB            = ""
}
Filters =
{
    Lomacor:
    {
        ID              = 1
        Active          = True
        Type            = "CyC_LOMACOR_MAPS_FILTER_TYPE"
        IsPublishable   = True
        ReplayFromDB    = False
        dt              = 1.0
        dt_Sequencing   = 1.0
        InputSources    = ()
        Parameters      = (
                            {name = "zenodo_url", value = "https://sandbox.zenodo.org/api/deposit/depositions"},
                            {name = "access_token", value = "LP7zVxmRWR4WTRVWNn8pMEnyBNxyTpAEui3E2pKPMZ00tpGdtzDrLZB2dgFN"},
                            {name = "region", value = "Brasov"},
                            {name = "maps_folder", value = "etc/env/maps"},
                            {name = "map", value = "2"},
                            {name = "map_filetype", value = ".map"},
                            {name = "map_upload_th", value = "5"},
                            {name = "mapper", value = "true"}
                          )
    }
}
